# Generated by Django 4.1.5 on 2023-02-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(default="READER", max_length=20),
        ),
    ]
