# Generated by Django 4.1.2 on 2022-11-16 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("author", models.CharField(max_length=64)),
                ("editor", models.CharField(max_length=64)),
                ("cover", models.CharField(max_length=200)),
                ("collection", models.CharField(max_length=12)),
            ],
        ),
    ]
