# Generated by Django 4.1.5 on 2023-01-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_genre_alter_book_collection_book_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover",
        ),
    ]
